revelation/ember-cli-revelation-ui

- bower.json
- package.json
- tests/dummy/app/templates/_buttons.hbs
Run `npm install --save` and `bower install --save` after rebasing/merging.
> Upgrade to Ember-data 2.0.0 Stable

- tests/dummy/app/components/header-anchor/template.hbs
- tests/dummy/app/styles/_dummy.sass
- tests/dummy/app/styles/app.sass
- tests/dummy/app/templates/application.hbs
- tests/dummy/app/templates/partials/_buttons.hbs
- Utilize `header-anchor` component.
- Use self-closing `<i />` tag for icons.
- Utilize `panel-code-example`.
- Sort partials into the appropriate directory.
- Move dummy styles into partial.
> Clean up buttons documentation

- tests/integration/components/rui-dropdown-trigger/component-test.js
- tests/unit/components/rui-button-test.js
...when the tests fail....DELETE!
> Fixes failing tests after update

- tests/dummy/app/components/color-swatch/component.js
- tests/dummy/app/components/color-swatch/template.hbs
- tests/dummy/app/styles/_dummy.sass
- tests/dummy/app/templates/partials/_colors.hbs
- Add typographical colors.
- Write documentation.
- Refactor `color-swatch` component.
- Add missing classes.
- Update style to occupy less space.
> Finish Colors Documentation

- tests/dummy/app/templates/navigation.hbs
- tests/dummy/app/templates/partials/_nav_stub.hbs
- Scaffold nav markup.
- Temporarily add nav_stub partial to navigation for review.
Here's the basic layout along with a taste of how we could set up the submenus without creating a specific class for them.
> Set up Nav layout

- tests/dummy/app/styles/_dummy.sass
- tests/dummy/app/styles/app.sass
- tests/dummy/app/styles/components/_nav_stub.sass
- tests/dummy/app/templates/partials/_nav_stub.hbs
- Add style for empty example links.
- Move nav styles into a partial.
- Refine nav layout styles.
- Add sub-sub menu example.
> Update Nav Styles

- ember-cli-build.js
- package.json
> Ks add autoprofixer

- addon/menu/service.js
- package.json
- tests/dummy/app/initializers/ember-cli-cookie.js
Adds ember-cli-cookie addon, adds initializer, injects into menu service, adds basic configuration
> COOKIES!!!

- addon/components/rui-nav-vertical/component.js
- addon/components/rui-nav-vertical/template.hbs
- tests/dummy/app/styles/components/_rui-nav-vertical.sass
- tests/dummy/app/templates/partials/_nav_vertical.hbs
- tests/dummy/app/templates/partials/layout/_sidebar.hbs
- Clean up documentation.
- Update rui-nav-vertical style to fit inside layout.
> Refactor rui-nav-vertical

- addon/components/rui-nav-project-dropdown/component.js
- tests/dummy/app/styles/_variables.scss
- tests/dummy/app/styles/app.sass
- tests/dummy/app/styles/components/_rui-buttons.sass
- tests/dummy/app/styles/components/_rui-dropdowns.sass
- tests/dummy/app/styles/components/_rui-nav-project-dropdown.sass
- tests/dummy/app/styles/components/_rui-typography.sass
- tests/dummy/app/templates/partials/layout/_sidebar.hbs
Adds markup and styles for the project selector...
> Ks project selector

- addon/components/rui-nav-project-dropdown/component.js
- addon/components/rui-nav-project-dropdown/template.hbs
- tests/dummy/app/templates/partials/layout/_sidebar.hbs
> Moves Project dropdown into component

- addon/components/rui-nav-vertical/template.hbs
- addon/styles/_rui-base.sass
- addon/styles/bootstrap/_variables.scss
- addon/styles/components/_rui-nav-vertical.sass
- Set up tertiary item class.
- Change default link color to gray.
- Sort component sass imports alphabetically.
> Revise `rui-vertical-nav` Component

- addon/components/rui-button/component.js
- tests/dummy/app/controllers/application.js
- tests/dummy/app/routes/application.js
- tests/dummy/app/templates/partials/_buttons.hbs
Now that that's applied learnin'!
- Refactors button action handling
- Unlimited parameters!
- Safe defaults
- 1/16th the size
- All the kids are doing it!
(Had to update docs and move actions to controller)
> Refactor rui-button action handling

- addon/components/rui-avatar/component.js
- addon/components/rui-button/template.hbs
- app/styles/components/_rui-avatar.sass
- app/styles/components/_rui-dropdown-trigger.sass
- app/styles/components/_rui-dropdowns.sass
- app/styles/components/_rui-nav-vertical.sass
- Replace icon with rui-spinner in loading button.
- Fix vertical nav link color.
- Fix dropup trigger chevron style.
Fixes #74
Fixes #69
> UI Cleanup

- .ember-cli
> Set default port to 4300.

- addon/components/rui-avatar/component.js
- addon/components/rui-dropdown-menu/component.js
- addon/components/rui-dropdown-trigger/component.js
- tests/dummy/app/templates/components.hbs
- tests/dummy/app/templates/partials/_avatar.hbs
- tests/dummy/app/templates/partials/_dropdowns.hbs
- tests/unit/components/rui-avatar-test.js
- tests/unit/components/rui-button-test.js
- tests/unit/components/rui-dropdown-menu-test.js
- tests/unit/components/rui-dropdown-test.js
- tests/unit/components/rui-dropdown-trigger-test.js
- tests/unit/components/rui-icon-test.js
- tests/unit/components/rui-input-checkbox-test.js
- tests/unit/components/rui-input-radio-test.js
- tests/unit/components/rui-input-text-test.js
- tests/unit/components/rui-spinner-test.js
> Unit Tests

- app/styles/bootstrap/_bootstrap.scss
You may need to run `ember g ember-cli-revelation-ui` from consuming app.
> Import bootstrap nav.

- app/styles/fonts/_imports.sass
To test a fix for ember-admin deploy
> deply testing

- app/styles/fonts/_imports.sass
Fixes the protocol for google font from http to https.
> Ab goog font staging test

- addon/pods/components/rui-button/component.js
Adds attribute binding to button component for testing purposes.
> Adds data-test-id attribute binding to btn component

- PULL_REQUEST_TEMPLATE.md
Update the pr template to include prompt for prs to include Closes and RFC fields to encourage usage.
> Add `Closes` and `RFC` fields for PR templates
